import express from "express";
import morgan from "morgan";
import cors from "cors";
import roomRoutes from "./routes/roomRoutes.js";
import staffRoutes from "./routes/staffRoutes.js";
import customerRoutes from "./routes/customerRoutes.js";
import bookingRoutes from "./routes/bookingRoutes.js";
import authRoutes from "./routes/authRoutes.js";
import dashboardRoutes from "./routes/dashboardRoutes.js";
import webRoomRoutes from "./routes/webRoomRoutes.js";
import webStaffRoutes from "./routes/webStaffRoutes.js";
import webBookingRoutes from "./routes/webBookingRoutes.js";
 const app=express();
 app.use(express.json());
 app.use(express.urlencoded({ extended: true }));
 app.use(cors());
 app.use(morgan("dev"));
 app.use("/api/room",roomRoutes);
 app.use("/api/staff",staffRoutes);
 app.use("/api/customer",customerRoutes);
 app.use("/api/booking",bookingRoutes);
 app.use("/api/auth", authRoutes);
 app.use("/api/dashboard",dashboardRoutes);
 app.use("/api/webrooms", webRoomRoutes);
app.use("/api/webstaff", webStaffRoutes);
app.use("/api/webbookings", webBookingRoutes);
 app.get("/test",(req,res)=>{
    res.send("API is running");
 });
 export default app;